config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users,              only: [:new, :create, :edit, :update, :index, :show]
    resources :orgs,               only: [:new, :create, :edit, :update, :index, :show]
    resources :perms,              only: [:new, :create, :edit, :update, :index, :show]
    resources :languages,          only: [:new, :create, :edit, :update, :index, :show]
    resources :templates,          only: [:new, :create, :edit, :update, :index, :show]
    resources :phases,             only: [:new, :create, :edit, :update, :index, :show]
    resources :sections,           only: [:new, :create, :edit, :update, :index, :show]
    resources :questions,          only: [:new, :create, :edit, :update, :index, :show]
    resources :question_formats,   only: [:new, :create, :edit, :update, :index, :show]
    resources :question_options,   only: [:new, :create, :edit, :update, :index, :show]
    resources :annotations,        only: [:new, :create, :edit, :update, :index, :show]
    resources :answers,            only: [:new, :create, :edit, :update, :index, :show]
    resources :guidances,          only: [:new, :create, :edit, :update, :index, :show]
    resources :guidance_groups,    only: [:new, :create, :edit, :update, :index, :show]
    resources :themes,             only: [:new, :create, :edit, :update, :index, :show]
    resources :notes,              only: [:new, :create, :edit, :update, :index, :show]
    resources :plans,              only: [:new, :create, :edit, :update, :index, :show]
    resources :identifier_schemes, only: [:new, :create, :edit, :update, :index, :show]
    resources :exported_plans,     only: [:new, :create, :edit, :update, :index, :show]
    resources :regions,            only: [:new, :create, :edit, :update, :index, :show]
    resources :roles,              only: [:new, :create, :edit, :update, :index, :show]
    resources :splash_logs,        only: [:new, :create, :edit, :update, :index, :show]
    resources :user_identifiers,   only: [:new, :create, :edit, :update, :index, :show]
resources :token_permission_types, only: [:new, :create, :edit, :update, :index, :show]
#resources :plans_guidance_groups

    root to: "users#index"
  end

  devise_for :users, controllers: {
        registrations: "registrations",
        passwords: 'passwords',
        sessions: 'sessions',
        omniauth_callbacks: 'users/omniauth_callbacks',
        invitations: 'users/invitations' } do

    get "/users/sign_out", :to => "devise/sessions#destroy"
  end

  # WAYFless access point - use query param idp
  #get 'auth/shibboleth' => 'users/omniauth_shibboleth_request#redirect', :as => 'user_omniauth_shibboleth'
  #get 'auth/shibboleth/assoc' => 'users/omniauth_shibboleth_request#associate', :as => 'user_shibboleth_assoc'
  #post '/auth/:provider/callback' => 'sessions#oauth_create'

  # fix for activeadmin signout bug
  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  delete '/users/identifiers/:id', to: 'user_identifiers#destroy', as: 'destroy_user_identifier'

  get '/orgs/shibboleth', to: 'orgs#shibboleth_ds', as: 'shibboleth_ds'
  get '/orgs/shibboleth/:org_name', to: 'orgs#shibboleth_ds_passthru'
  post '/orgs/shibboleth', to: 'orgs#shibboleth_ds_passthru'
  get '/users/ldap_username', to: 'users#ldap_username'
  post '/users/ldap_account', to: 'users#ldap_account'

  resources :users, path: 'users', only: [] do
    member do
      put 'update_email_preferences'
      put 'org_swap', constraints: {format: [:json]}
    end
    post '/acknowledge_notification', to: 'users#acknowledge_notification'
  end

  #organisation admin area
  resources :users, :path => 'org/admin/users', only: [] do
    collection do
      get 'admin_index'
    end
    member do
      get 'admin_grant_permissions'
      put 'admin_update_permissions'
      put 'activate'
    end
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  patch 'locale/:locale' => 'application#set_locale_session', as: 'locale'

  root :to => 'home#index'
    get "about_us" => 'static_pages#about_us'
    get "help" => 'static_pages#help'
    get "roadmap" => 'static_pages#roadmap'
    get "terms" => 'static_pages#termsuse'
    get "privacy" => 'static_pages#privacy'
    get "public_plans" => 'public_pages#plan_index'
    get "public_templates" => 'public_pages#template_index'
    get "template_export/:id" => 'public_pages#template_export', as: 'template_export'
    get "plan_export/:id" => 'public_pages#plan_export', as: 'plan_export'
    get "existing_users" => 'existing_users#index'
    
    # DMPTool specific documentation pages
    get "get_started" => 'public_pages#get_started', as: 'get_started'
    get "promote" => 'static_pages#promote'
    get "researchers" => 'static_pages#researchers'
    get "faq" => 'static_pages#faq'
    get "general_guidance" => 'static_pages#general_guidance'
    get "quick_start_guide" => 'static_pages#help'
    get "news_media" => 'static_pages#news_media'
    get "public_orgs" => 'public_pages#orgs'

    #post 'contact_form' => 'contacts', as: 'localized_contact_creation'
    #get 'contact_form' => 'contacts#new', as: 'localized_contact_form'

    resources :orgs, :path => 'org/admin', only: [] do
      member do
        get 'children'
        get 'templates'
        get 'admin_show'
        get 'admin_edit'
        put 'admin_update'
      end

      get 'logo', constraints: {format: :json}
    end

    resources :guidances, :path => 'org/admin/guidance', only: [] do
      member do
        get 'admin_show'
        get 'admin_index'
        get 'admin_edit'
        get 'admin_new'
        delete 'admin_destroy'
        post 'admin_create'
        put 'admin_update'
        put 'admin_publish'
        put 'admin_unpublish'
        get 'update_phases'
        get 'update_versions'
        get 'update_sections'
        get 'update_questions'
      end
    end

    resources :guidance_groups, :path => 'org/admin/guidancegroup', only: [] do
      member do
        get 'admin_show'
        get 'admin_new'
        get 'admin_edit'
        delete 'admin_destroy'
        post 'admin_create'
        put 'admin_update'
        put 'admin_update_publish'
        put 'admin_update_unpublish'
      end
    end

    resources :answers, only: [] do
      post 'create_or_update', on: :collection
    end

    # Question Formats controller, currently just the one action
    get 'question_formats/rda_api_address' => 'question_formats#rda_api_address'

    resources :notes, only: [:create, :update, :archive] do
      member do
        patch 'archive'
      end
    end

    resources :plans do
      member do
        get 'status'
        get 'locked'
        get 'answer'
        put 'update_guidance_choices'
        post 'delete_recent_locks'
        post 'lock_section', constraints: {format: [:html, :json]}
        post 'unlock_section', constraints: {format: [:html, :json]}
        post 'unlock_all_sections'
        get 'warning'
        get 'section_answers'
        get 'share'
        get 'download'
        post 'duplicate'
        get 'export'
        post 'invite'
        post 'visibility', constraints: {format: [:json]}
        post 'set_test', constraints: {format: [:json]}
        get 'request_feedback'
        get 'overview'
        get 'phase_status'
      end

      collection do
        get 'possible_templates'
        get 'possible_guidance'
      end
    end

    resources :usage, only: [:index]

    resources :roles, only: [:create, :update, :destroy] do
      member do
        put :deactivate
      end
    end

    namespace :settings do
      resources :plans, only: [:update]
    end

    resources :token_permission_types, only: [:index]

    namespace :api, defaults: {format: :json} do
      namespace :v0 do
        resources :guidances, only: [:index], controller: 'guidance_groups', path: 'guidances'
        resources :plans, only: :create
        resources :templates, only: :index
        resource  :statistics, only: [], controller: "statistics", path: "statistics" do
          member do
            get :users_joined
            get :completed_plans
            get :created_plans
            get :using_template
            get :plans_by_template
            get :plans
          end
        end
      end
    end

    namespace :paginable do
      resources :orgs, only: [] do
        get 'public/:page', action: :public, on: :collection, as: :public
        get 'index/:page', action: :index, on: :collection, as: :index
      end
      # Paginable actions for plans
      resources :plans, only: [] do
        get 'privately_visible/:page', action: :privately_visible, on: :collection, as: :privately_visible
        get 'organisationally_or_publicly_visible/:page', action: :organisationally_or_publicly_visible, on: :collection, as: :organisationally_or_publicly_visible
        get 'publicly_visible/:page', action: :publicly_visible, on: :collection, as: :publicly_visible
        get 'org_admin/:page', action: :org_admin, on: :collection, as: :org_admin
      end
      # Paginable actions for users
      resources :users, only: [] do
        get 'index/:page', action: :index, on: :collection, as: :index
      end
      # Paginable actions for themes
      resources :themes, only: [] do
        get 'index/:page', action: :index, on: :collection, as: :index
      end
      # Paginable actions for notifications
      resources :notifications, only: [] do
        get 'index/:page', action: :index, on: :collection, as: :index
      end
      # Paginable actions for templates
      resources :templates, only: [] do
        get 'index/:page', action: :index, on: :collection, as: :index
        get 'customisable/:page', action: :customisable, on: :collection, as: :customisable
        get 'organisational/:page', action: :organisational, on: :collection, as: :organisational

app/controllers/org_admin/phases_controller.rb
module OrgAdmin
  class PhasesController < ApplicationController
    include Versionable
    
    after_action :verify_authorized

    # GET /org_admin/templates/:template_id/phases/[:id]
    def show
      phase = Phase.includes(:template, :sections).order(:number).find(params[:id])
      authorize phase
      if !phase.template.latest?
        flash[:notice] = _('You are viewing a historical version of this template. You will not be able to make changes.')
      end
      section = params.fetch(:section, nil)
      render('container',
        locals: { 
          partial_path: 'show',
          template: phase.template,
          phase: phase,
          sections: phase.sections.order(:number).select(:id, :title, :modifiable),
          current_section: section.present? ? Section.find_by(id: section, phase_id: phase.id) : nil
        })
    end

    # GET /org_admin/templates/:template_id/phases/[:id]/edit
    def edit
      phase = Phase.includes(:template).find(params[:id])
      authorize phase
      section = params.fetch(:section, nil)
      # User cannot edit a phase if its a customization so redirect to show
      if phase.template.customization_of.present? || !phase.template.latest?
        redirect_to org_admin_template_phase_path(template_id: phase.template, id: phase.id, section: section)
      else
        render('container',
          locals: { 
            partial_path: 'edit',
            template: phase.template,
            phase: phase,
            sections: phase.sections.order(:number).select(:id, :title, :modifiable),
            current_section: section.present? ? Section.find_by(id: section, phase_id: phase.id) : nil
          })
      end
    end

    #preview a phase
    # GET /org_admin/phases/[:id]/preview
    def preview
      phase = Phase.includes(:template).find(params[:id])
      authorize phase
      render('/org_admin/phases/preview', 
        locals: {
          template: phase.template,
          phase: phase
        })
    end

    #add a new phase to a passed template
    # GET /org_admin/phases/new
    def new
      template = Template.includes(:phases).find(params[:template_id])
      if template.latest?
        nbr = template.phases.maximum(:number)
        phase = Phase.new({
          template: template,
          modifiable: true,
          number: (nbr.present? ? nbr + 1 : 1)
        })
        authorize phase
        render('/org_admin/templates/container',
          locals: {
            partial_path: 'new',
            template: template,
            phase: phase,
            referrer: request.referrer.present? ? request.referrer : org_admin_templates_path
          })
      else
        render org_admin_templates_path, alert: _('You canot add a phase to a historical version of a template.')
      end
    end
        
    #create a phase
    # POST /org_admin/phases
    def create
      phase = Phase.new(phase_params)
      phase.template = Template.find(params[:template_id])
      authorize phase
      begin
        phase = get_new(phase)
        phase.modifiable = true
        if phase.save!
          flash[:notice] = success_message(_('phase'), _('created'))
        else
          flash[:alert] = failed_create_error(phase, _('phase'))
        end
      rescue StandardError => e
        flash[:alert] = _('Unable to create a new version of this template.')
      end
      if flash[:alert].present?
        redirect_to edit_org_admin_template_path(id: phase.template_id)
      else
        redirect_to edit_org_admin_template_phase_path(template_id: phase.template.id, id: phase.id)
      end
    end

    #update a phase of a template
    # PUT /org_admin/phases/[:id]
    def update
      phase = Phase.find(params[:id])
      authorize phase
      begin
        phase = get_modifiable(phase)
        if phase.update!(phase_params)
          flash[:notice] = success_message(_('phase'), _('updated'))
        else
          flash[:alert] = failed_update_error(phase, _('phase'))
        end
      rescue StandardError => e
        flash[:alert] = _('Unable to create a new version of this template.')
      end
      redirect_to edit_org_admin_template_phase_path(template_id: phase.template.id, id: phase.id)
    end

    #delete a phase
    # DELETE org_admin/phases/[:id]
    def destroy
      phase = Phase.includes(:template).find(params[:id])
      authorize phase
      begin
        phase = get_modifiable(phase)
        template = phase.template
        if phase.destroy!
          flash[:notice] = success_message(_('phase'), _('deleted'))
        else
          flash[:alert] = failed_destroy_error(phase, _('phase'))
        end
      rescue StandardError => e
        flash[:alert] = _('Unable to create a new version of this template.')
      end
      
      if flash[:alert].present?
        redirect_to org_admin_template_phase_path(template.id, phase.id)
      else
        redirect_to edit_org_admin_template_path(template)
      end
    end

    private
      def phase_params
        params.require(:phase).permit(:title, :description, :number)
      end
  end
end

app/controllers/org_admin/plans_controller.rb
module OrgAdmin
  class PlansController < ApplicationController
    # GET org_admin/plans
    def index
      # Test auth directly and throw Pundit error sincePundit is unaware of namespacing
      raise Pundit::NotAuthorizedError unless current_user.present? && current_user.can_org_admin?
      
      vals = Role.access_values_for(:reviewer)
      @feedback_plans = Plan.joins(:roles).where('roles.user_id = ? and roles.access IN (?)', current_user.id, vals)
      @plans = current_user.org.plans
    end
    
    # GET org_admin/plans/:id/feedback_complete
    def feedback_complete
      plan = Plan.find(params[:id])
      # Test auth directly and throw Pundit error sincePundit is unaware of namespacing
      raise Pundit::NotAuthorizedError unless current_user.present? && current_user.can_org_admin?
      raise Pundit::NotAuthorizedError unless plan.reviewable_by?(current_user.id)
      
      if plan.complete_feedback(current_user)
        redirect_to org_admin_plans_path, notice: _('%{plan_owner} has been notified that you have finished providing feedback') % { plan_owner: plan.owner.name(false) }
      else
        redirect_to org_admin_plans_path, alert: _('Unable to notify user that you have finished providing feedback.')
      end
    end
    
    # GET /org_admin/download_plans
    def download_plans
      # Test auth directly and throw Pundit error sincePundit is unaware of namespacing
      raise Pundit::NotAuthorizedError unless current_user.present? && current_user.can_org_admin?
      
      org = current_user.org
      file_name = org.name.gsub(/ /, "_")
      header_cols = [
        "#{_('Project title')}",
        "#{_('Template')}",
        "#{_('Organisation')}",
        "#{_('Owner name')}",
        "#{_('Owner email')}",
        "#{_('Updated')}",
        "#{_('Visibility')}"
      ]
      
      plans = CSV.generate do |csv|
        csv << header_cols
        org.plans.includes(template: :org).order(updated_at: :desc).each do |plan|
          owner = plan.owner
          csv << [
            "#{plan.title}", 
            "#{plan.template.title}", 
            "#{plan.owner.org.present? ? plan.owner.org.name : ''}", 
            "#{plan.owner.name(false)}",
            "#{plan.owner.email}",
            "#{l(plan.latest_update.to_date, formats: :short)}",
            "#{Plan.visibility_message(plan.visibility.to_sym).capitalize}"
          ] 
        end
      end

      respond_to do |format|
        format.csv  { send_data plans,  filename: "#{file_name}.csv" }
      end
    end
  end
end

app/views/org_admin/phases/_edit.html.erb
<%= form_for phase, { url: org_admin_template_phase_path(template.id, phase.id), html: { method: :put, class: 'phase_form' }} do |f| %>
  <%= render partial: 'org_admin/phases/form', locals: local_assigns.merge({ f: f }) %>
<% end %>

app/views/org_admin/phases/_form.html.erb
<%= f.hidden_field :template_id, value: template.id%>
<div class="form-group col-md-10">
  <%= f.label(:title, _('Title') ,class: "control-label") %>
  <%= f.text_field(:title, class: "form-control", 'aria-required': true, 'data-toggle': 'tooltip', title: _('Enter a title for the phase e.g. intial DMP, full DMP... This is what users will see in the tabs when completing a plan. If you only have one phase, call it something generic e.g. Glasgow DMP')) %> 
</div>

<div class="form-group">
  <div class="col-md-10">
    <%= f.label(:number, _('Order of display'), class: "control-label") %>
  </div>
  <div class="col-md-4">
    <%= f.number_field(:number, in: 1..5, class: "form-control", 'aria-required': true, 'data-toggle': 'tooltip', title: _('This allows you to order the phases of your template.')) %>
  </div>
</div>

<div class="form-group col-md-10" data-toggle="tooltip" title="<%= _("Enter a basic description. This will be presented to users on the 'Admin Plan' tab, above the summary of the sections and questions which they will be asked to answer.") %>">
  <%= f.label(:description, _('Description'), class: "control-label") %>
  <%= f.text_area(:description, class: "phase") %>
</div>

<div class="form-group col-md-4 pull-right">   
  <%= f.button(_('Save'), class: 'btn btn-default', type: "submit") %>
</div>

app/views/org_admin/phases/_index.html.erb
<div class="row">
  <div class="col-md-12">
    <% if template_hash[:template][:phases].present? && template_hash[:template][:phases].length > 1 %>
      <div id="sections-accordion-controls">
        <div class="accordion-controls" data-parent="phases_accordion">
          <a href="#" data-toggle-direction="show"><%= _('expand all') %></a>
          <span>|</span>
          <a href="#" data-toggle-direction="hide"><%= _('collapse all') %></a>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="panel-group" id="phases_accordion" role="tablist">
      <!-- If template has phases-->
      <% if template_hash[:template][:phases].present? %>
        <% i = 0 %>
        <% template_hash[:template][:phases].each do |phase_no, phase_hash| %>
          <% phase = phase_hash[:data] %>
            <div class="panel panel-default">
              <div class="heading-button" role="button" data-toggle="collapse"
                   data-parent="phases_accordion" 
                   href="#collapsePhase<%= phase.id %>"
                   aria-expanded="<%= i == 0 ? 'true' : 'false' %>" 
                   aria-controls="#collapsePhase<%= phase.id %>">
                   
                <div class="panel-heading" role="tab" id="<%= "headingPhase#{phase.id}" %>">
                  <div class="panel-title pull-left">
                    <%= phase.title %>
                  </div>
                  <div class="pull-right">
                    <i class="fa fa-plus pull-right" aria-hidden="true"></i>
                  </div>
                  <div class="clearfix"></div>
                </div>
              </div>
              <div id="<%= "collapsePhase#{phase.id}" %>" class="panel-collapse collapse<%= i == 0 ? 'in' : '' %>" role="tabpanel" aria-labelledby="<%= "headingPhase#{phase.id}" %>"<%= i == 0 ? 'aria-expanded="true"' : '' %>>
                <div class="panel-body">
                  <%= render partial: 'org_admin/templates/show_phases_sections', locals: { phase: phase, phase_hash: phase_hash, template: template, current: current } %>
                </div>
              </div>
            </div>
            <% i += 1 %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/org_admin/phases/_new.html.erb
<h2><%= _('Phase details') %></h2>
<p><%= _('When you create a new phase for your template, a version will automatically be created. Once you complete the form below you will be provided with options to create sections and questions.') %></p>
<%= form_for phase, { url: org_admin_template_phases_path(template), html: { class: 'phase_form' } } do |f| %>
  <%= render partial: 'org_admin/phases/form', locals: local_assigns.merge({ f: f }) %>
<% end %>

app/views/org_admin/phases/_overview.html.erb
<br>
<h2><%= _('Template Overview') %></h2>
<% phases.each do |phase| %>
  <hr>
  <div class="row">
    <div class="col-md-12">
      <div>
        <h3>
          <%= phase.title %>
          <div class="pull-right">
            <% if template.customization_of.present? && template.latest? %>
              <%= link_to _('Customize phase'), org_admin_template_phase_path(template.id, phase.id), { class: "btn btn-default", role: 'button' } %>
            <% elsif modifiable %>
              <%= link_to _('Edit phase'), edit_org_admin_template_phase_path(template.id, phase.id), { class: "btn btn-default", role: 'button' } %>
            <% else %>
              <%= link_to _('Show phase'), org_admin_template_phase_path(template.id, phase.id), { class: "btn btn-default", role: 'button' } %>
            <% end %>
            <% if template.latest? && phase.modifiable %>
              <%= link_to _('Delete phase'), org_admin_template_phase_path(template.id, phase.id),
                          data: { confirm: _("You are about to delete the '%{phase_title}' phase. This will remove all of the sections and questions listed below. Are you sure?") % { phase_title: phase.title }, 
                                  length: 20, omission: _('... (continued)') }, method: :delete, class: 'btn btn-default', role: 'button' %>
            <% end %>
          </div>
        </h3>
        <p class="pull-left">
          <%= raw phase.description %>
        </p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <% if phase.sections.length > 0 %>
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th><%= _('Sections')%></th>
                <th><%= _('Questions')%></th>
              </tr>
            </thead>
            <tbody>
              <% phase.sections.each do |section| %>
                <tr>
                  <td><p><%= section.title %></p></td>
                  <td>
                    <% if section.questions.present? %>
                      <ul>
                        <% section.questions.each do |question| %>
                          <li>
                            <%= raw question.text %>
                            <% if question.question_options.length > 0 %>
                              <ul>
                                <% question.question_options.each do |option| %>
                                  <li><%= option.text %></li>
                                <% end %>
                              </ul>
                            <% end %>
                          </li>
                        <% end %>
                      </ul>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/org_admin/phases/_show.html.erb
<dl class="dl-horizontal">
  <dt><%= _('Title') %></dt>
  <dd><%= phase.title %></dd>
  <dt><%= _('Order of display') %></dt>
  <dd><%= phase.number %></dd>
  <dt><%= _('Description') %></dt>
  <dd><%= raw phase.description %></dd>
</dl>

app/views/org_admin/phases/container.html.erb
<% modifiable = template.latest? && !template.customization_of.present? && template.id.present? && (template.org_id = current_user.org.id) %>
<div class="row">
  <div class="col-md-12">
    <h1><%= template.title %></h1>
    <% referrer = template.customization_of.present? ? customisable_org_admin_templates_path : organisational_org_admin_templates_path %>
    <%= link_to _('View all templates'), referrer, class: 'btn btn-default pull-right' %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <!-- render navigation tabs for the template-->
    <%= render partial: "/org_admin/templates/navigation", locals: local_assigns.merge({ modifiable: modifiable }) %>
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active">
        <div class="panel panel-default">
          <div class="panel-body">
            <% # locals: { phase, template, edit, current_section } %>
            <div class="pull-left">
              <h2><%= _('Phase details')%></h2>
            </div>
            <div class="pull-right">
              <%= link_to(_('Preview'), preview_org_admin_template_phase_path(template, phase), { class: 'btn btn-default phase_preview_link', role: 'button' }) %>
            </div>
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12">
                <%= render partial: partial_path, locals: local_assigns.merge({ modifiable: modifiable }) %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <h2><%= _('Sections') %></h2>
                <% if phase.sections.length > 1 %>
                  <div id="sections-accordion-controls">
                    <div class="accordion-controls" data-parent="sections_accordion">
                      <a href="#" data-toggle-direction="show"><%= _('expand all') %></a>
                      <span>|</span>
                      <a href="#" data-toggle-direction="hide"><%= _('collapse all') %></a>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <%= render partial: 'org_admin/sections/index', locals: local_assigns.merge({ modifiable: modifiable }) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/org_admin/phases/preview.html.erb
<% modifiable = template.latest? && !template.customization_of.present? && template.id.present? && (template.org_id = current_user.org.id) %>
<div class="row">
  <div class="col-md-12">
    <h1><%= template.title %></h1>
    <div class="pull-right">
      <ul class="list-inline">
        <% if template.latest? %>
          <% if template.customization_of.present? %>
            <li><%= link_to _('Back to customise phase'), org_admin_template_phase_path(template_id: template.id, id: phase.id), class: 'btn btn-primary' %></li>
          <% else %>
            <li><%= link_to _('Back to edit phase'), edit_org_admin_template_phase_path(template_id: template.id, id: phase.id), class: 'btn btn-primary' %></li>
          <% end %>
        <% else %>
          <li><%= link_to _('Back to phase'), org_admin_template_phase_path(template_id: template.id, id: phase.id), class: 'btn btn-primary' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <%= link_to _('Write plan'), '#', class: 'preview-tab' %>
      </li>
    </ul>

    <!-- render phase below -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active">
        <div class="panel panel-default">
          <div class="panel-body">
            <%= render partial: '/phases/edit_plan_answers', 
                  locals: {
                    plan: nil, 
                    phase: phase, 
                    readonly: true, 
                    question_guidance: {}, 
                    edit: false, 
                    guidance_groups: [], 
                    base_template_org: template.base_org } %>
          </div>
        </div>
      </div>
    </div>
    
  </div>
</div>