config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users,              only: [:new, :create, :edit, :update, :index, :show]
    resources :orgs,               only: [:new, :create, :edit, :update, :index, :show]
    resources :perms,              only: [:new, :create, :edit, :update, :index, :show]
    resources :languages,          only: [:new, :create, :edit, :update, :index, :show]
    resources :templates,          only: [:new, :create, :edit, :update, :index, :show]
    resources :phases,             only: [:new, :create, :edit, :update, :index, :show]
    resources :sections,           only: [:new, :create, :edit, :update, :index, :show]
    resources :questions,          only: [:new, :create, :edit, :update, :index, :show]
    resources :question_formats,   only: [:new, :create, :edit, :update, :index, :show]
    resources :question_options,   only: [:new, :create, :edit, :update, :index, :show]
    resources :annotations,        only: [:new, :create, :edit, :update, :index, :show]
    resources :answers,            only: [:new, :create, :edit, :update, :index, :show]
    resources :guidances,          only: [:new, :create, :edit, :update, :index, :show]
    resources :guidance_groups,    only: [:new, :create, :edit, :update, :index, :show]
    resources :themes,             only: [:new, :create, :edit, :update, :index, :show]
    resources :notes,              only: [:new, :create, :edit, :update, :index, :show]
    resources :plans,              only: [:new, :create, :edit, :update, :index, :show]
    resources :identifier_schemes, only: [:new, :create, :edit, :update, :index, :show]
    resources :exported_plans,     only: [:new, :create, :edit, :update, :index, :show]
    resources :regions,            only: [:new, :create, :edit, :update, :index, :show]
    resources :roles,              only: [:new, :create, :edit, :update, :index, :show]
    resources :splash_logs,        only: [:new, :create, :edit, :update, :index, :show]
    resources :user_identifiers,   only: [:new, :create, :edit, :update, :index, :show]
resources :token_permission_types, only: [:new, :create, :edit, :update, :index, :show]
#resources :plans_guidance_groups

    root to: "users#index"
  end

  devise_for :users, controllers: {
        registrations: "registrations",
        passwords: 'passwords',
        sessions: 'sessions',
        omniauth_callbacks: 'users/omniauth_callbacks',
        invitations: 'users/invitations' } do

    get "/users/sign_out", :to => "devise/sessions#destroy"
  end

  # WAYFless access point - use query param idp
  #get 'auth/shibboleth' => 'users/omniauth_shibboleth_request#redirect', :as => 'user_omniauth_shibboleth'
  #get 'auth/shibboleth/assoc' => 'users/omniauth_shibboleth_request#associate', :as => 'user_shibboleth_assoc'
  #post '/auth/:provider/callback' => 'sessions#oauth_create'

  # fix for activeadmin signout bug
  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  delete '/users/identifiers/:id', to: 'user_identifiers#destroy', as: 'destroy_user_identifier'

  get '/orgs/shibboleth', to: 'orgs#shibboleth_ds', as: 'shibboleth_ds'
  get '/orgs/shibboleth/:org_name', to: 'orgs#shibboleth_ds_passthru'
  post '/orgs/shibboleth', to: 'orgs#shibboleth_ds_passthru'
  get '/users/ldap_username', to: 'users#ldap_username'
  post '/users/ldap_account', to: 'users#ldap_account'

  resources :users, path: 'users', only: [] do
    member do
      put 'update_email_preferences'
      put 'org_swap', constraints: {format: [:json]}
    end
    post '/acknowledge_notification', to: 'users#acknowledge_notification'
  end

  #organisation admin area
  resources :users, :path => 'org/admin/users', only: [] do
    collection do
      get 'admin_index'
    end
    member do
      get 'admin_grant_permissions'
      put 'admin_update_permissions'
      put 'activate'
    end
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  patch 'locale/:locale' => 'application#set_locale_session', as: 'locale'

  root :to => 'home#index'
    get "about_us" => 'static_pages#about_us'
    get "help" => 'static_pages#help'
    get "roadmap" => 'static_pages#roadmap'
    get "terms" => 'static_pages#termsuse'
    get "privacy" => 'static_pages#privacy'
    get "public_plans" => 'public_pages#plan_index'
    get "public_templates" => 'public_pages#template_index'
    get "template_export/:id" => 'public_pages#template_export', as: 'template_export'
    get "plan_export/:id" => 'public_pages#plan_export', as: 'plan_export'
    get "existing_users" => 'existing_users#index'
    
    # DMPTool specific documentation pages
    get "get_started" => 'public_pages#get_started', as: 'get_started'
    get "promote" => 'static_pages#promote'
    get "researchers" => 'static_pages#researchers'
    get "faq" => 'static_pages#faq'
    get "general_guidance" => 'static_pages#general_guidance'
    get "quick_start_guide" => 'static_pages#help'
    get "news_media" => 'static_pages#news_media'
    get "public_orgs" => 'public_pages#orgs'

    #post 'contact_form' => 'contacts', as: 'localized_contact_creation'
    #get 'contact_form' => 'contacts#new', as: 'localized_contact_form'

    resources :orgs, :path => 'org/admin', only: [] do
      member do
        get 'children'
        get 'templates'
        get 'admin_show'
        get 'admin_edit'
        put 'admin_update'
      end

      get 'logo', constraints: {format: :json}
    end

    resources :guidances, :path => 'org/admin/guidance', only: [] do
      member do
        get 'admin_show'
        get 'admin_index'
        get 'admin_edit'
        get 'admin_new'
        delete 'admin_destroy'
        post 'admin_create'
        put 'admin_update'
        put 'admin_publish'
        put 'admin_unpublish'
        get 'update_phases'
        get 'update_versions'
        get 'update_sections'
        get 'update_questions'
      end
    end

    resources :guidance_groups, :path => 'org/admin/guidancegroup', only: [] do
      member do
        get 'admin_show'
        get 'admin_new'
        get 'admin_edit'
        delete 'admin_destroy'
        post 'admin_create'
        put 'admin_update'
        put 'admin_update_publish'
        put 'admin_update_unpublish'
      end
    end

    resources :answers, only: [] do
      post 'create_or_update', on: :collection
    end

    # Question Formats controller, currently just the one action
    get 'question_formats/rda_api_address' => 'question_formats#rda_api_address'

    resources :notes, only: [:create, :update, :archive] do
      member do
        patch 'archive'
      end
    end

    resources :plans do
      member do
        get 'status'
        get 'locked'
        get 'answer'
        put 'update_guidance_choices'
        post 'delete_recent_locks'
        post 'lock_section', constraints: {format: [:html, :json]}
        post 'unlock_section', constraints: {format: [:html, :json]}
        post 'unlock_all_sections'
        get 'warning'
        get 'section_answers'
        get 'share'
        get 'download'
        post 'duplicate'
        get 'export'
        post 'invite'
        post 'visibility', constraints: {format: [:json]}
        post 'set_test', constraints: {format: [:json]}
        get 'request_feedback'
        get 'overview'
        get 'phase_status'
      end

      collection do
        get 'possible_templates'
        get 'possible_guidance'
      end
    end

    resources :usage, only: [:index]

    resources :roles, only: [:create, :update, :destroy] do
      member do
        put :deactivate
      end
    end

    namespace :settings do
      resources :plans, only: [:update]
    end

    resources :token_permission_types, only: [:index]

    namespace :api, defaults: {format: :json} do
      namespace :v0 do
        resources :guidances, only: [:index], controller: 'guidance_groups', path: 'guidances'
        resources :plans, only: :create
        resources :templates, only: :index
        resource  :statistics, only: [], controller: "statistics", path: "statistics" do
          member do
            get :users_joined
            get :completed_plans
            get :created_plans
            get :using_template
            get :plans_by_template
            get :plans
          end
        end
      end
    end

    namespace :paginable do
      resources :orgs, only: [] do
        get 'public/:page', action: :public, on: :collection, as: :public
        get 'index/:page', action: :index, on: :collection, as: :index
      end
      # Paginable actions for plans
      resources :plans, only: [] do
        get 'privately_visible/:page', action: :privately_visible, on: :collection, as: :privately_visible
        get 'organisationally_or_publicly_visible/:page', action: :organisationally_or_publicly_visible, on: :collection, as: :organisationally_or_publicly_visible
        get 'publicly_visible/:page', action: :publicly_visible, on: :collection, as: :publicly_visible
        get 'org_admin/:page', action: :org_admin, on: :collection, as: :org_admin
      end
      # Paginable actions for users
      resources :users, only: [] do
        get 'index/:page', action: :index, on: :collection, as: :index
      end
      # Paginable actions for themes
      resources :themes, only: [] do
        get 'index/:page', action: :index, on: :collection, as: :index
      end
      # Paginable actions for notifications
      resources :notifications, only: [] do
        get 'index/:page', action: :index, on: :collection, as: :index
      end
      # Paginable actions for templates
      resources :templates, only: [] do
        get 'index/:page', action: :index, on: :collection, as: :index
        get 'customisable/:page', action: :customisable, on: :collection, as: :customisable
        get 'organisational/:page', action: :organisational, on: :collection, as: :organisational

app/controllers/api/v0/plans_controller.rb
module Api
  module V0
    class PlansController < Api::V0::BaseController
      before_action :authenticate

      ##
      # Creates a new plan based on the information passed in JSON to the API
      def create
        @template = Template.live(params[:template_id])
        raise Pundit::NotAuthorizedError unless Api::V0::PlansPolicy.new(@user, @template).create?

        plan_user = User.find_by(email: params[:plan][:email])
        # ensure user exists
        if plan_user.blank?
          User.invite!({email: params[:plan][:email]}, ( @user))
          plan_user = User.find_by(email: params[:plan][:email])
          plan_user.org = @user.org
          plan_user.save
        end
        # ensure user's organisation is the same as api user's 
        raise Pundit::NotAuthorizedError, _("user must be in your organisation") unless plan_user.org == @user.org

        # initialize the plan
        @plan = Plan.new
        @plan.principal_investigator = plan_user.surname.blank? ? nil : "#{plan_user.firstname} #{plan_user.surname}"
        @plan.data_contact = plan_user.email
        # set funder name to template's org, or original template's org
        if @template.customization_of.nil?
          @plan.funder_name = @template.org.name
        else
          @plan.funder_name = Template.where(family_id: @template.customization_of).first.org.name
        end
        @plan.template = @template
        @plan.title = params[:plan][:title]
        if @plan.save
          @plan.assign_creator(plan_user)
          respond_with @plan
        else
          # the plan did not save 
          self.headers['WWW-Authenticate'] = "Token realm=\"\""
          render json: _("Bad Parameters"), status: 400
        end
      end


    end
  end
end

app/controllers/org_admin/plans_controller.rb
module OrgAdmin
  class PlansController < ApplicationController
    # GET org_admin/plans
    def index
      # Test auth directly and throw Pundit error sincePundit is unaware of namespacing
      raise Pundit::NotAuthorizedError unless current_user.present? && current_user.can_org_admin?
      
      vals = Role.access_values_for(:reviewer)
      @feedback_plans = Plan.joins(:roles).where('roles.user_id = ? and roles.access IN (?)', current_user.id, vals)
      @plans = current_user.org.plans
    end
    
    # GET org_admin/plans/:id/feedback_complete
    def feedback_complete
      plan = Plan.find(params[:id])
      # Test auth directly and throw Pundit error sincePundit is unaware of namespacing
      raise Pundit::NotAuthorizedError unless current_user.present? && current_user.can_org_admin?
      raise Pundit::NotAuthorizedError unless plan.reviewable_by?(current_user.id)
      
      if plan.complete_feedback(current_user)
        redirect_to org_admin_plans_path, notice: _('%{plan_owner} has been notified that you have finished providing feedback') % { plan_owner: plan.owner.name(false) }
      else
        redirect_to org_admin_plans_path, alert: _('Unable to notify user that you have finished providing feedback.')
      end
    end
    
    # GET /org_admin/download_plans
    def download_plans
      # Test auth directly and throw Pundit error sincePundit is unaware of namespacing
      raise Pundit::NotAuthorizedError unless current_user.present? && current_user.can_org_admin?
      
      org = current_user.org
      file_name = org.name.gsub(/ /, "_")
      header_cols = [
        "#{_('Project title')}",
        "#{_('Template')}",
        "#{_('Organisation')}",
        "#{_('Owner name')}",
        "#{_('Owner email')}",
        "#{_('Updated')}",
        "#{_('Visibility')}"
      ]
      
      plans = CSV.generate do |csv|
        csv << header_cols
        org.plans.includes(template: :org).order(updated_at: :desc).each do |plan|
          owner = plan.owner
          csv << [
            "#{plan.title}", 
            "#{plan.template.title}", 
            "#{plan.owner.org.present? ? plan.owner.org.name : ''}", 
            "#{plan.owner.name(false)}",
            "#{plan.owner.email}",
            "#{l(plan.latest_update.to_date, formats: :short)}",
            "#{Plan.visibility_message(plan.visibility.to_sym).capitalize}"
          ] 
        end
      end

      respond_to do |format|
        format.csv  { send_data plans,  filename: "#{file_name}.csv" }
      end
    end
  end
end

app/controllers/paginable/guidance_groups_controller.rb
module Paginable 
  class GuidanceGroupsController < ApplicationController
    include Paginable
    # /paginable/guidance_groups/index/:page
    def index
      authorize(Guidance)
      paginable_renderise(partial: 'index',
        scope: GuidanceGroup.by_org(current_user.org))
    end
  end
end

app/controllers/paginable/guidances_controller.rb
module Paginable 
  class GuidancesController < ApplicationController
    include Paginable
    # /paginable/guidances/index/:page
    def index
      authorize(Guidance)
      paginable_renderise(partial: 'index',
        scope: Guidance.by_org(current_user.org).includes(:guidance_group, :themes))
    end
  end
end

app/controllers/paginable/notifications_controller.rb
module Paginable
  class NotificationsController < ApplicationController
    include Paginable
    # /paginable/notifications/index/:page
    def index
      authorize(Notification)
      paginable_renderise(partial: 'index', scope: Notification.all)
    end
  end
end

app/controllers/paginable/themes_controller.rb
module Paginable 
  class ThemesController < ApplicationController
    include Paginable
    # /paginable/themes/index/:page
    def index
      authorize(Theme)
      paginable_renderise(partial: 'index', scope: Theme.all)
    end
  end
end

app/helpers/paginable_helper.rb
module PaginableHelper
  include Paginable
end

app/helpers/plans_helper.rb
module PlansHelper
  # Shows whether the user has default, template-default or custom settings
  # for the given plan.
  # --------------------------------------------------------
  def plan_settings_indicator(plan)
    plan_settings     = plan.super_settings(:export)
    template_settings = plan.template.try(:settings, :export)

    key = if plan_settings.try(:value?)
      plan_settings.formatting == template_settings.formatting ? "template_formatting" : "custom_formatting"
    elsif template_settings.try(:value?)
      "template_formatting"
    else
      "default_formatting"
    end

    content_tag(:small, t("helpers.settings.plans.#{key}"))
  end

  # display the role of the user for a given plan
  def display_role(role)
    if role.creator?
      access = _('Owner')
      
    else
      case role.access_level
        when 3
          access = _('Co-owner')
        when 2
          access = _('Editor')
        when 1
          access = _('Read only')
      end
    end
    return access
  end

  # display the visibility of the plan
  def display_visibility(val)
    case val
    when 'organisationally_visible'
      return "<span title=\"#{ visibility_tooltip(val) }\">#{_('Organisation')}</span>"
    when 'publicly_visible'
      return "<span title=\"#{ visibility_tooltip(val) }\">#{_('Public')}</span>"
    when 'privately_visible'
      return "<span title=\"#{ visibility_tooltip(val) }\">#{_('Private')}</span>"
    else
      return "<span>#{_('Private')}</span>" # Test Plans
    end
  end
  
  def visibility_tooltip(val)
    case val
    when 'organisationally_visible'
      return _('Organisation: anyone at my organisation can view.')
    when 'publicly_visible'
      return _('Public: anyone can view.')
    else
      return _('Private: restricted to me and people I invite.')
    end
  end
end

app/views/paginable/plans/_org_admin.html.erb
<div class="table-responsive">
  <table class="table table-hover" id="my-plans">
    <thead>
      <tr>
        <th><%= _('Project Title') %>&nbsp;<%= paginable_sort_link('plans.title') %></th>
        <th><%= _('Template') %>&nbsp;<%= paginable_sort_link('templates.title') %></th>
        <th><%= _('Organisation') %></th>
        <th><%= _('Owner') %></th>
        <th class="last-edited"><%= _('Updated') %>&nbsp;<%= paginable_sort_link('plans.updated_at') %></th>
        <th><%= _('Visibility') %></th>
      </tr>
    </thead>
    <tbody>
      <% scope.each do |plan| %>
        <tr>
          <td>
            <%= link_to "#{plan.title.length > 60 ? "#{plan.title[0..59]} ..." : plan.title}", plan_path(plan) %>
          </td>
          <td><%= plan.template.title %></td>
          <td><%= plan.users.first.org.name %></td>
          <td><%= plan.users.first.name(false) %></td>
          <td><%= l(plan.updated_at.to_date, formats: :short) %></td>
          <td class="plan-visibility">
            <%= plan.visibility === 'is_test' ? _('Test') : raw(display_visibility(plan.visibility)) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/paginable/plans/_organisationally_or_publicly_visible.html.erb
<% if current_user.org_id.present? %>
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th><%= _('Project Title') %>&nbsp;<%= paginable_sort_link('plans.title') %></th>
                                <th><%= _('Template') %>&nbsp;<%= paginable_sort_link('templates.title') %></th>
                                <th><%= _('Owner') %></th>
                                <th class="last-edited"><%= _('Updated') %>&nbsp;<%= paginable_sort_link('plans.updated_at') %></th>
                                <th class="sorter-false"><%= _('Download') %></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% scope.each do |plan| %>
                                <tr>
                                    <td><%= plan.title.length > 40 ? "#{plan.title[0..39]} ..." : plan.title %></td>
                                    <td><%= plan.template.title %></td>
                                    <td><%= plan.owner.present? ? plan.owner.name : _('Unknown') %></td>
                                    <td><%= l(plan.updated_at.to_date, formats: :short) %></td>
                                    <td class="text-center">
                                        <%= link_to _('PDF'), plan_export_path(plan, format: :pdf), target: '_blank' %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
<% end %>

app/views/paginable/plans/_privately_visible.html.erb
      <div class="table-responsive">
        <table class="table table-hover" id="my-plans">
          <thead>
            <tr>
              <th><%= _('Project Title') %>&nbsp;<%= paginable_sort_link('plans.title') %></th>
              <th><%= _('Template') %>&nbsp;<%= paginable_sort_link('templates.title') %></th>
              <th class="last-edited"><%= _('Edited') %>&nbsp;<%= paginable_sort_link('plans.updated_at') %></th>
              <th><%= _('Role') %></th>
              <th class="text-center sorter-false"><%= _('Test') %></th>
              <th><%= _('Visibility') %></th>
              <th><%= _('Shared') %></th>
              <th class="sorter-false">
                <span aria-hidden="false" class="sr-only"><%= _('Actions') %></span>
              </th>
            </tr>
          </thead>
          <tbody>
            <% scope.each do |plan| %>
              <tr>
                <td>
                  <%= link_to "#{plan.title.length > 60 ? "#{plan.title[0..59]} ..." : plan.title}",
                      plan_path(plan) %>
                </td>
                <td><%= plan.template.title %></td>
                <td><%= l(plan.updated_at.to_date, formats: :short) %></td>
                <td><%= display_role(plan.roles.find_by(user: current_user)) %></td>
                <td class="text-center">
                  <% if plan.administerable_by?(current_user.id) then %>
                    <%= form_for plan, url: set_test_plan_path(plan), html: { method: :post, class: 'set_test_plan', remote: true } do |f| %>
                      <%= check_box_tag(:is_test, "1", (plan.visibility === 'is_test')) %>
                      <%= f.submit(_('Update'), style: 'display:none') %>
                    <% end %>
                  <% else %>
                    <%= plan.visibility === 'is_test' ? _('Yes') : _('No') %>
                  <% end %>
                </td>
                <td class="plan-visibility">
                  <%= plan.visibility === 'is_test' ? _('N/A') : raw(display_visibility(plan.visibility)) %>
                </td>
                <td>
                  <% if plan.shared %>
                    <%= _("Yes") %>
                  <% else %>
                    <%= _('No') %>
                  <% end  %>
                </td>
                <td>
                  <div class="dropdown">
                    <button class="btn btn-link dropdown-toggle" type="button"
                            id="plan-<%= plan.id %>-actions" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="true">
                      <%= _('Actions') %><span class="caret"></span>
                    </button>

                    <ul class="dropdown-menu" aria-labelledby="plan-<%= plan.id %>-actions">
                    <% if plan.editable_by?(current_user.id) then %>
                      <li><%= link_to _('Edit'), plan_path(plan) %></li>
                      
                      <% if plan.administerable_by?(current_user.id) %>
                        <li><%= link_to _('Share'), share_plan_path(plan) %></li>
                      <% end %>

                      <li><%= link_to _('Download'), download_plan_path(plan) %></li>
                      <li><%= link_to(_('Make a copy'), duplicate_plan_path(plan), data: { method: :post }) %></li>
                    <% else %>
                      <li><%= link_to _('View'), plan_path(plan) %></li>
                      
                      <% if !plan.reviewable_by?(current_user.id) %>
                        <li><%= link_to _('Download'), download_plan_path(plan) %></li>
                      <% end %>
                    <% end %>
                    <% role = plan.roles.where(user_id: current_user.id).first %>
                    <% conf = (role.creator? && plan.publicly_visible?) ? _("Are you sure you wish to remove this public plan? This will remove it from the Public DMPs page but any collaborators will still be able to access it.") : _("Are you sure you wish to remove this plan? Any collaborators will still be able to access it.") %>
                    <li><%= link_to _('Remove'), deactivate_role_path(role), 'data-method': 'put', rel: 'nofollow', 'data-confirm': conf %></li>
                  </ul>
                </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

app/views/paginable/plans/_publicly_visible.html.erb
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= _('Project Title') %>&nbsp;<%= paginable_sort_link('plans.title') %></th>
        <th><%= _('Template') %>&nbsp;<%= paginable_sort_link('templates.title') %></th>
        <th><%= _('Organisation') %></th>
        <th><%= _('Owner') %></th>
        <th class="sorter-false text-center"><%= _('Download') %></th>
      </tr>
    </thead>
    <tbody>
      <% scope.each do |plan| %>
        <tr class="table-data">
          <td><%= plan.title %></td>
          <td><%= plan.template.title %></td>
          <td><%= (plan.owner.nil? || plan.owner.org.nil? ? _('Not Applicable') : plan.owner.org.name) %></td>
          <td><%= (plan.owner.nil? ? _('Unknown') : plan.owner.name(false)) %></td>
          <td class="text-center">
            <%= link_to _('PDF'), plan_export_path(plan, format: :pdf), class: "dmp_table_link", target: '_blank' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>